import { Post, User } from "./types";

export const users: User[] = [
  {
    id: "user1",
    username: "marcos_dev",
    name: "Marcos Willian",
    image: "https://i.pravatar.cc/150?u=user1",
    bio: "Fullstack dev passionate about clean code.",
  },
  {
    id: "user2",
    username: "lara_js",
    name: "Lara Silva",
    image: "https://i.pravatar.cc/150?u=user2",
    bio: "Frontend developer and React enthusiast.",
  },
  {
    id: "user3",
    username: "pedro_data",
    name: "Pedro Almeida",
    image: "https://i.pravatar.cc/150?u=user3",
    bio: "Data nerd and coffee lover.",
  },
  {
    id: "user4",
    username: "ana_uiux",
    name: "Ana Costa",
    image: "https://i.pravatar.cc/150?u=user4",
    bio: "Designing intuitive experiences.",
  },
  {
    id: "user5",
    username: "ricardo_code",
    name: "Ricardo Matos",
    image: "https://i.pravatar.cc/150?u=user5",
    bio: "Mobile dev exploring Kotlin and Swift.",
  },
];

export const posts: Post[] = [
  {
    id: "post1",
    createdAt: "2025-06-19T10:00:00Z",
    content: "Just started a new side project with Next.js and Tailwind!",
    user_id: "user1",
    user: users[0],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "post2",
    createdAt: "2025-06-19T10:10:00Z",
    content: "Congrats! Looking forward to seeing the result!",
    user_id: "user2",
    user: users[1],
    parent_id: "post1",
    parent: null,
    replies: [],
  },
  {
    id: "post3",
    createdAt: "2025-06-19T11:00:00Z",
    content: "What do you use for state management in larger React apps?",
    user_id: "user3",
    user: users[2],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "post4",
    createdAt: "2025-06-19T11:05:00Z",
    content: "Zustand is my current favorite for most apps.",
    user_id: "user1",
    user: users[0],
    parent_id: "post3",
    parent: null,
    replies: [],
  },
  {
    id: "post5",
    createdAt: "2025-06-19T11:15:00Z",
    content: "I still prefer Redux Toolkit for the ecosystem.",
    user_id: "user2",
    user: users[1],
    parent_id: "post3",
    parent: null,
    replies: [],
  },
  {
    id: "post6",
    createdAt: "2025-06-19T12:00:00Z",
    content: "Spent the weekend learning about Clean Architecture!",
    user_id: "user4",
    user: users[3],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "post7",
    createdAt: "2025-06-19T12:10:00Z",
    content: "Nice! It really helps with scaling projects.",
    user_id: "user5",
    user: users[4],
    parent_id: "post6",
    parent: null,
    replies: [],
  },
  {
    id: "post8",
    createdAt: "2025-06-19T12:20:00Z",
    content: "Been diving into animations with Framer Motion. Amazing!",
    user_id: "user4",
    user: users[3],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "post9",
    createdAt: "2025-06-19T13:00:00Z",
    content: "Anyone using Expo with Dev Client in production?",
    user_id: "user5",
    user: users[4],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "post10",
    createdAt: "2025-06-19T13:05:00Z",
    content: "Yes! Works great if you control the environment.",
    user_id: "user1",
    user: users[0],
    parent_id: "post9",
    parent: null,
    replies: [],
  },
  {
    id: "post11",
    createdAt: "2025-06-19T13:10:00Z",
    content: "Expo Router is also super helpful.",
    user_id: "user2",
    user: users[1],
    parent_id: "post9",
    parent: null,
    replies: [],
  },
  {
    id: "post12",
    createdAt: "2025-06-19T14:00:00Z",
    content: "Who else prefers light mode? 😂",
    user_id: "user3",
    user: users[2],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "post13",
    createdAt: "2025-06-19T14:10:00Z",
    content: "Dark mode supremacy!",
    user_id: "user4",
    user: users[3],
    parent_id: "post12",
    parent: null,
    replies: [],
  },
  {
    id: "post14",
    createdAt: "2025-06-19T14:15:00Z",
    content: "Depends on the lighting. 😂",
    user_id: "user5",
    user: users[4],
    parent_id: "post12",
    parent: null,
    replies: [],
  },
  {
    id: "post15",
    createdAt: "2025-06-19T14:30:00Z",
    content: "Deployments are smoother with CI/CD setup. GitHub Actions FTW!",
    user_id: "user1",
    user: users[0],
    parent_id: null,
    parent: null,
    replies: [],
  },
];
